# Generated by Django 6.0.2 on 2026-06-05 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='postcode',
        ),
        migrations.AddField(
            model_name='entry',
            name='address',
            field=models.TextField(default='Not provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
