# Generated by Django 6.0.2 on 2026-06-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='preferred_gift_card',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('Apple', 'Apple'), ('Google Play', 'Google Play'), ('PlayStation', 'PlayStation'), ('Xbox', 'Xbox'), ('Tesco', 'Tesco'), ('Asos', 'ASOS'), ('One4All', 'One4All'), ('Paypal', 'PayPal')], default='Amazon', max_length=50),
            preserve_default=False,
        ),
    ]
