# Generated by Django 6.0.2 on 2026-06-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_entry_preferred_gift_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='preferred_gift_card',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('Apple', 'Apple'), ('Google Play', 'Google Play'), ('PlayStation', 'PlayStation'), ('Xbox', 'Xbox'), ('Tesco', 'Tesco'), ('Asos', 'ASOS'), ('One4All', 'One4All'), ('Paypal', 'PayPal')], max_length=50),
        ),
    ]
